test:
  prop: testValue


server:
  port: 80

spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/mybatis
      username: root
      password: 991116
      driver-class-name: com.mysql.jdbc.Driver

testcase:
  book:
    id: ${random.int}
    name: ${random.value}
    uuid: ${random.uuid}
    publishTime: ${random.long}
